# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D4C4BA
background         #171615
cursor             #796E68

active_tab_foreground     #171615
active_tab_background     #D4C4BA
inactive_tab_foreground   #D4C4BA
inactive_tab_background   #171615

active_border_color   #D4C4BA
inactive_border_color #171615
bell_border_color     #14100E

color0      #3E3D3C
color1		#14100E
color2		#171210
color3		#211A13
color4		#483021
color5		#4F3523
color6		#62402C
color7		#B9A295
color8		#817168
color9		#1A1513
color10		#1F1815
color11		#2C221A
color12		#60402C
color13		#6A462F
color14		#83553B
color15		#B9A295
